name: Push Container to Heroku

on:
    push:
      branches: [ backend ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Complete processing to Heroku
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: cd backend && heroku container:login && heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web && heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 